extends:
  - 'devextreme/typescript'
  - 'devextreme/javascript'
  - 'devextreme/spell-check'
  - 'devextreme/jest'
parserOptions:
  createDefaultProgram: true
  project: './tsconfig.json'
overrides:
  - files:
      - '*.ts'
    parser: '@typescript-eslint/parser'
    extends:
      - 'devextreme/typescript'
    rules:
      '@typescript-eslint/no-explicit-any': 'error'

